# encoding: utf-8
# module PySide2.QtWidgets
# from C:\Users\siddh\AppData\Local\Programs\Python\Python37\lib\site-packages\PySide2\QtWidgets.pyd
# by generator 1.146
# no doc

# imports
import PySide2.QtCore as __PySide2_QtCore
import PySide2.QtGui as __PySide2_QtGui
import Shiboken as __Shiboken


class QStyle(__PySide2_QtCore.QObject):
    # no doc
    def alignedRect(self, *args, **kwargs): # real signature unknown
        pass

    def combinedLayoutSpacing(self, *args, **kwargs): # real signature unknown
        pass

    def drawComplexControl(self, *args, **kwargs): # real signature unknown
        pass

    def drawControl(self, *args, **kwargs): # real signature unknown
        pass

    def drawItemPixmap(self, *args, **kwargs): # real signature unknown
        pass

    def drawItemText(self, *args, **kwargs): # real signature unknown
        pass

    def drawPrimitive(self, *args, **kwargs): # real signature unknown
        pass

    def generatedIconPixmap(self, *args, **kwargs): # real signature unknown
        pass

    def hitTestComplexControl(self, *args, **kwargs): # real signature unknown
        pass

    def itemPixmapRect(self, *args, **kwargs): # real signature unknown
        pass

    def itemTextRect(self, *args, **kwargs): # real signature unknown
        pass

    def layoutSpacing(self, *args, **kwargs): # real signature unknown
        pass

    def pixelMetric(self, *args, **kwargs): # real signature unknown
        pass

    def polish(self, *args, **kwargs): # real signature unknown
        pass

    def proxy(self, *args, **kwargs): # real signature unknown
        pass

    def sizeFromContents(self, *args, **kwargs): # real signature unknown
        pass

    def sliderPositionFromValue(self, *args, **kwargs): # real signature unknown
        pass

    def sliderValueFromPosition(self, *args, **kwargs): # real signature unknown
        pass

    def standardIcon(self, *args, **kwargs): # real signature unknown
        pass

    def standardPalette(self, *args, **kwargs): # real signature unknown
        pass

    def standardPixmap(self, *args, **kwargs): # real signature unknown
        pass

    def styleHint(self, *args, **kwargs): # real signature unknown
        pass

    def subControlRect(self, *args, **kwargs): # real signature unknown
        pass

    def subElementRect(self, *args, **kwargs): # real signature unknown
        pass

    def unpolish(self, *args, **kwargs): # real signature unknown
        pass

    def visualAlignment(self, *args, **kwargs): # real signature unknown
        pass

    def visualPos(self, *args, **kwargs): # real signature unknown
        pass

    def visualRect(self, *args, **kwargs): # real signature unknown
        pass

    def __init__(self, *args, **kwargs): # real signature unknown
        pass

    @staticmethod # known case of __new__
    def __new__(*args, **kwargs): # real signature unknown
        """ Create and return a new object.  See help(type) for accurate signature. """
        pass

    CC_ComboBox = None # (!) real value is ''
    CC_CustomBase = None # (!) real value is ''
    CC_Dial = None # (!) real value is ''
    CC_GroupBox = None # (!) real value is ''
    CC_MdiControls = None # (!) real value is ''
    CC_ScrollBar = None # (!) real value is ''
    CC_Slider = None # (!) real value is ''
    CC_SpinBox = None # (!) real value is ''
    CC_TitleBar = None # (!) real value is ''
    CC_ToolButton = None # (!) real value is ''
    CE_CheckBox = None # (!) real value is ''
    CE_CheckBoxLabel = None # (!) real value is ''
    CE_ColumnViewGrip = None # (!) real value is ''
    CE_ComboBoxLabel = None # (!) real value is ''
    CE_CustomBase = None # (!) real value is ''
    CE_DockWidgetTitle = None # (!) real value is ''
    CE_FocusFrame = None # (!) real value is ''
    CE_Header = None # (!) real value is ''
    CE_HeaderEmptyArea = None # (!) real value is ''
    CE_HeaderLabel = None # (!) real value is ''
    CE_HeaderSection = None # (!) real value is ''
    CE_ItemViewItem = None # (!) real value is ''
    CE_MenuBarEmptyArea = None # (!) real value is ''
    CE_MenuBarItem = None # (!) real value is ''
    CE_MenuEmptyArea = None # (!) real value is ''
    CE_MenuHMargin = None # (!) real value is ''
    CE_MenuItem = None # (!) real value is ''
    CE_MenuScroller = None # (!) real value is ''
    CE_MenuTearoff = None # (!) real value is ''
    CE_MenuVMargin = None # (!) real value is ''
    CE_ProgressBar = None # (!) real value is ''
    CE_ProgressBarContents = None # (!) real value is ''
    CE_ProgressBarGroove = None # (!) real value is ''
    CE_ProgressBarLabel = None # (!) real value is ''
    CE_PushButton = None # (!) real value is ''
    CE_PushButtonBevel = None # (!) real value is ''
    CE_PushButtonLabel = None # (!) real value is ''
    CE_RadioButton = None # (!) real value is ''
    CE_RadioButtonLabel = None # (!) real value is ''
    CE_RubberBand = None # (!) real value is ''
    CE_ScrollBarAddLine = None # (!) real value is ''
    CE_ScrollBarAddPage = None # (!) real value is ''
    CE_ScrollBarFirst = None # (!) real value is ''
    CE_ScrollBarLast = None # (!) real value is ''
    CE_ScrollBarSlider = None # (!) real value is ''
    CE_ScrollBarSubLine = None # (!) real value is ''
    CE_ScrollBarSubPage = None # (!) real value is ''
    CE_ShapedFrame = None # (!) real value is ''
    CE_SizeGrip = None # (!) real value is ''
    CE_Splitter = None # (!) real value is ''
    CE_TabBarTab = None # (!) real value is ''
    CE_TabBarTabLabel = None # (!) real value is ''
    CE_TabBarTabShape = None # (!) real value is ''
    CE_ToolBar = None # (!) real value is ''
    CE_ToolBoxTab = None # (!) real value is ''
    CE_ToolBoxTabLabel = None # (!) real value is ''
    CE_ToolBoxTabShape = None # (!) real value is ''
    CE_ToolButtonLabel = None # (!) real value is ''
    ComplexControl = None # (!) real value is ''
    ContentsType = None # (!) real value is ''
    ControlElement = None # (!) real value is ''
    CT_CheckBox = None # (!) real value is ''
    CT_ComboBox = None # (!) real value is ''
    CT_CustomBase = None # (!) real value is ''
    CT_DialogButtons = None # (!) real value is ''
    CT_GroupBox = None # (!) real value is ''
    CT_HeaderSection = None # (!) real value is ''
    CT_ItemViewItem = None # (!) real value is ''
    CT_LineEdit = None # (!) real value is ''
    CT_MdiControls = None # (!) real value is ''
    CT_Menu = None # (!) real value is ''
    CT_MenuBar = None # (!) real value is ''
    CT_MenuBarItem = None # (!) real value is ''
    CT_MenuItem = None # (!) real value is ''
    CT_ProgressBar = None # (!) real value is ''
    CT_PushButton = None # (!) real value is ''
    CT_RadioButton = None # (!) real value is ''
    CT_ScrollBar = None # (!) real value is ''
    CT_SizeGrip = None # (!) real value is ''
    CT_Slider = None # (!) real value is ''
    CT_SpinBox = None # (!) real value is ''
    CT_Splitter = None # (!) real value is ''
    CT_TabBarTab = None # (!) real value is ''
    CT_TabWidget = None # (!) real value is ''
    CT_ToolButton = None # (!) real value is ''
    PE_CustomBase = None # (!) real value is ''
    PE_Frame = None # (!) real value is ''
    PE_FrameButtonBevel = None # (!) real value is ''
    PE_FrameButtonTool = None # (!) real value is ''
    PE_FrameDefaultButton = None # (!) real value is ''
    PE_FrameDockWidget = None # (!) real value is ''
    PE_FrameFocusRect = None # (!) real value is ''
    PE_FrameGroupBox = None # (!) real value is ''
    PE_FrameLineEdit = None # (!) real value is ''
    PE_FrameMenu = None # (!) real value is ''
    PE_FrameStatusBar = None # (!) real value is ''
    PE_FrameStatusBarItem = None # (!) real value is ''
    PE_FrameTabBarBase = None # (!) real value is ''
    PE_FrameTabWidget = None # (!) real value is ''
    PE_FrameWindow = None # (!) real value is ''
    PE_IndicatorArrowDown = None # (!) real value is ''
    PE_IndicatorArrowLeft = None # (!) real value is ''
    PE_IndicatorArrowRight = None # (!) real value is ''
    PE_IndicatorArrowUp = None # (!) real value is ''
    PE_IndicatorBranch = None # (!) real value is ''
    PE_IndicatorButtonDropDown = None # (!) real value is ''
    PE_IndicatorCheckBox = None # (!) real value is ''
    PE_IndicatorColumnViewArrow = None # (!) real value is ''
    PE_IndicatorDockWidgetResizeHandle = None # (!) real value is ''
    PE_IndicatorHeaderArrow = None # (!) real value is ''
    PE_IndicatorItemViewItemCheck = None # (!) real value is ''
    PE_IndicatorItemViewItemDrop = None # (!) real value is ''
    PE_IndicatorMenuCheckMark = None # (!) real value is ''
    PE_IndicatorProgressChunk = None # (!) real value is ''
    PE_IndicatorRadioButton = None # (!) real value is ''
    PE_IndicatorSpinDown = None # (!) real value is ''
    PE_IndicatorSpinMinus = None # (!) real value is ''
    PE_IndicatorSpinPlus = None # (!) real value is ''
    PE_IndicatorSpinUp = None # (!) real value is ''
    PE_IndicatorTabClose = None # (!) real value is ''
    PE_IndicatorTabTear = None # (!) real value is ''
    PE_IndicatorTabTearLeft = None # (!) real value is ''
    PE_IndicatorTabTearRight = None # (!) real value is ''
    PE_IndicatorToolBarHandle = None # (!) real value is ''
    PE_IndicatorToolBarSeparator = None # (!) real value is ''
    PE_IndicatorViewItemCheck = None # (!) real value is ''
    PE_PanelButtonBevel = None # (!) real value is ''
    PE_PanelButtonCommand = None # (!) real value is ''
    PE_PanelButtonTool = None # (!) real value is ''
    PE_PanelItemViewItem = None # (!) real value is ''
    PE_PanelItemViewRow = None # (!) real value is ''
    PE_PanelLineEdit = None # (!) real value is ''
    PE_PanelMenu = None # (!) real value is ''
    PE_PanelMenuBar = None # (!) real value is ''
    PE_PanelScrollAreaCorner = None # (!) real value is ''
    PE_PanelStatusBar = None # (!) real value is ''
    PE_PanelTipLabel = None # (!) real value is ''
    PE_PanelToolBar = None # (!) real value is ''
    PE_Widget = None # (!) real value is ''
    PixelMetric = None # (!) real value is ''
    PM_ButtonDefaultIndicator = None # (!) real value is ''
    PM_ButtonIconSize = None # (!) real value is ''
    PM_ButtonMargin = None # (!) real value is ''
    PM_ButtonShiftHorizontal = None # (!) real value is ''
    PM_ButtonShiftVertical = None # (!) real value is ''
    PM_CheckBoxLabelSpacing = None # (!) real value is ''
    PM_ComboBoxFrameWidth = None # (!) real value is ''
    PM_CustomBase = None # (!) real value is ''
    PM_DefaultChildMargin = None # (!) real value is ''
    PM_DefaultFrameWidth = None # (!) real value is ''
    PM_DefaultLayoutSpacing = None # (!) real value is ''
    PM_DefaultTopLevelMargin = None # (!) real value is ''
    PM_DialogButtonsButtonHeight = None # (!) real value is ''
    PM_DialogButtonsButtonWidth = None # (!) real value is ''
    PM_DialogButtonsSeparator = None # (!) real value is ''
    PM_DockWidgetFrameWidth = None # (!) real value is ''
    PM_DockWidgetHandleExtent = None # (!) real value is ''
    PM_DockWidgetSeparatorExtent = None # (!) real value is ''
    PM_DockWidgetTitleBarButtonMargin = None # (!) real value is ''
    PM_DockWidgetTitleMargin = None # (!) real value is ''
    PM_ExclusiveIndicatorHeight = None # (!) real value is ''
    PM_ExclusiveIndicatorWidth = None # (!) real value is ''
    PM_FocusFrameHMargin = None # (!) real value is ''
    PM_FocusFrameVMargin = None # (!) real value is ''
    PM_HeaderDefaultSectionSizeHorizontal = None # (!) real value is ''
    PM_HeaderDefaultSectionSizeVertical = None # (!) real value is ''
    PM_HeaderGripMargin = None # (!) real value is ''
    PM_HeaderMargin = None # (!) real value is ''
    PM_HeaderMarkSize = None # (!) real value is ''
    PM_IconViewIconSize = None # (!) real value is ''
    PM_IndicatorHeight = None # (!) real value is ''
    PM_IndicatorWidth = None # (!) real value is ''
    PM_LargeIconSize = None # (!) real value is ''
    PM_LayoutBottomMargin = None # (!) real value is ''
    PM_LayoutHorizontalSpacing = None # (!) real value is ''
    PM_LayoutLeftMargin = None # (!) real value is ''
    PM_LayoutRightMargin = None # (!) real value is ''
    PM_LayoutTopMargin = None # (!) real value is ''
    PM_LayoutVerticalSpacing = None # (!) real value is ''
    PM_ListViewIconSize = None # (!) real value is ''
    PM_MaximumDragDistance = None # (!) real value is ''
    PM_MDIFrameWidth = None # (!) real value is ''
    PM_MDIMinimizedWidth = None # (!) real value is ''
    PM_MdiSubWindowFrameWidth = None # (!) real value is ''
    PM_MdiSubWindowMinimizedWidth = None # (!) real value is ''
    PM_MenuBarHMargin = None # (!) real value is ''
    PM_MenuBarItemSpacing = None # (!) real value is ''
    PM_MenuBarPanelWidth = None # (!) real value is ''
    PM_MenuBarVMargin = None # (!) real value is ''
    PM_MenuButtonIndicator = None # (!) real value is ''
    PM_MenuDesktopFrameWidth = None # (!) real value is ''
    PM_MenuHMargin = None # (!) real value is ''
    PM_MenuPanelWidth = None # (!) real value is ''
    PM_MenuScrollerHeight = None # (!) real value is ''
    PM_MenuTearoffHeight = None # (!) real value is ''
    PM_MenuVMargin = None # (!) real value is ''
    PM_MessageBoxIconSize = None # (!) real value is ''
    PM_ProgressBarChunkWidth = None # (!) real value is ''
    PM_RadioButtonLabelSpacing = None # (!) real value is ''
    PM_ScrollBarExtent = None # (!) real value is ''
    PM_ScrollBarSliderMin = None # (!) real value is ''
    PM_ScrollView_ScrollBarOverlap = None # (!) real value is ''
    PM_ScrollView_ScrollBarSpacing = None # (!) real value is ''
    PM_SizeGripSize = None # (!) real value is ''
    PM_SliderControlThickness = None # (!) real value is ''
    PM_SliderLength = None # (!) real value is ''
    PM_SliderSpaceAvailable = None # (!) real value is ''
    PM_SliderThickness = None # (!) real value is ''
    PM_SliderTickmarkOffset = None # (!) real value is ''
    PM_SmallIconSize = None # (!) real value is ''
    PM_SpinBoxFrameWidth = None # (!) real value is ''
    PM_SpinBoxSliderHeight = None # (!) real value is ''
    PM_SplitterWidth = None # (!) real value is ''
    PM_SubMenuOverlap = None # (!) real value is ''
    PM_TabBarBaseHeight = None # (!) real value is ''
    PM_TabBarBaseOverlap = None # (!) real value is ''
    PM_TabBarIconSize = None # (!) real value is ''
    PM_TabBarScrollButtonWidth = None # (!) real value is ''
    PM_TabBarTabHSpace = None # (!) real value is ''
    PM_TabBarTabOverlap = None # (!) real value is ''
    PM_TabBarTabShiftHorizontal = None # (!) real value is ''
    PM_TabBarTabShiftVertical = None # (!) real value is ''
    PM_TabBarTabVSpace = None # (!) real value is ''
    PM_TabBar_ScrollButtonOverlap = None # (!) real value is ''
    PM_TabCloseIndicatorHeight = None # (!) real value is ''
    PM_TabCloseIndicatorWidth = None # (!) real value is ''
    PM_TextCursorWidth = None # (!) real value is ''
    PM_TitleBarButtonIconSize = None # (!) real value is ''
    PM_TitleBarButtonSize = None # (!) real value is ''
    PM_TitleBarHeight = None # (!) real value is ''
    PM_ToolBarExtensionExtent = None # (!) real value is ''
    PM_ToolBarFrameWidth = None # (!) real value is ''
    PM_ToolBarHandleExtent = None # (!) real value is ''
    PM_ToolBarIconSize = None # (!) real value is ''
    PM_ToolBarItemMargin = None # (!) real value is ''
    PM_ToolBarItemSpacing = None # (!) real value is ''
    PM_ToolBarSeparatorExtent = None # (!) real value is ''
    PM_ToolTipLabelFrameWidth = None # (!) real value is ''
    PM_TreeViewIndentation = None # (!) real value is ''
    PrimitiveElement = None # (!) real value is ''
    RequestSoftwareInputPanel = None # (!) real value is ''
    RSIP_OnMouseClick = None # (!) real value is ''
    RSIP_OnMouseClickAndAlreadyFocused = None # (!) real value is ''
    SC_All = None # (!) real value is ''
    SC_ComboBoxArrow = None # (!) real value is ''
    SC_ComboBoxEditField = None # (!) real value is ''
    SC_ComboBoxFrame = None # (!) real value is ''
    SC_ComboBoxListBoxPopup = None # (!) real value is ''
    SC_CustomBase = None # (!) real value is ''
    SC_DialGroove = None # (!) real value is ''
    SC_DialHandle = None # (!) real value is ''
    SC_DialTickmarks = None # (!) real value is ''
    SC_GroupBoxCheckBox = None # (!) real value is ''
    SC_GroupBoxContents = None # (!) real value is ''
    SC_GroupBoxFrame = None # (!) real value is ''
    SC_GroupBoxLabel = None # (!) real value is ''
    SC_MdiCloseButton = None # (!) real value is ''
    SC_MdiMinButton = None # (!) real value is ''
    SC_MdiNormalButton = None # (!) real value is ''
    SC_None = None # (!) real value is ''
    SC_ScrollBarAddLine = None # (!) real value is ''
    SC_ScrollBarAddPage = None # (!) real value is ''
    SC_ScrollBarFirst = None # (!) real value is ''
    SC_ScrollBarGroove = None # (!) real value is ''
    SC_ScrollBarLast = None # (!) real value is ''
    SC_ScrollBarSlider = None # (!) real value is ''
    SC_ScrollBarSubLine = None # (!) real value is ''
    SC_ScrollBarSubPage = None # (!) real value is ''
    SC_SliderGroove = None # (!) real value is ''
    SC_SliderHandle = None # (!) real value is ''
    SC_SliderTickmarks = None # (!) real value is ''
    SC_SpinBoxDown = None # (!) real value is ''
    SC_SpinBoxEditField = None # (!) real value is ''
    SC_SpinBoxFrame = None # (!) real value is ''
    SC_SpinBoxUp = None # (!) real value is ''
    SC_TitleBarCloseButton = None # (!) real value is ''
    SC_TitleBarContextHelpButton = None # (!) real value is ''
    SC_TitleBarLabel = None # (!) real value is ''
    SC_TitleBarMaxButton = None # (!) real value is ''
    SC_TitleBarMinButton = None # (!) real value is ''
    SC_TitleBarNormalButton = None # (!) real value is ''
    SC_TitleBarShadeButton = None # (!) real value is ''
    SC_TitleBarSysMenu = None # (!) real value is ''
    SC_TitleBarUnshadeButton = None # (!) real value is ''
    SC_ToolButton = None # (!) real value is ''
    SC_ToolButtonMenu = None # (!) real value is ''
    SE_CheckBoxClickRect = None # (!) real value is ''
    SE_CheckBoxContents = None # (!) real value is ''
    SE_CheckBoxFocusRect = None # (!) real value is ''
    SE_CheckBoxIndicator = None # (!) real value is ''
    SE_CheckBoxLayoutItem = None # (!) real value is ''
    SE_ComboBoxFocusRect = None # (!) real value is ''
    SE_ComboBoxLayoutItem = None # (!) real value is ''
    SE_CustomBase = None # (!) real value is ''
    SE_DateTimeEditLayoutItem = None # (!) real value is ''
    SE_DialogButtonBoxLayoutItem = None # (!) real value is ''
    SE_DockWidgetCloseButton = None # (!) real value is ''
    SE_DockWidgetFloatButton = None # (!) real value is ''
    SE_DockWidgetIcon = None # (!) real value is ''
    SE_DockWidgetTitleBarText = None # (!) real value is ''
    SE_FrameContents = None # (!) real value is ''
    SE_FrameLayoutItem = None # (!) real value is ''
    SE_GroupBoxLayoutItem = None # (!) real value is ''
    SE_HeaderArrow = None # (!) real value is ''
    SE_HeaderLabel = None # (!) real value is ''
    SE_ItemViewItemCheckIndicator = None # (!) real value is ''
    SE_ItemViewItemDecoration = None # (!) real value is ''
    SE_ItemViewItemFocusRect = None # (!) real value is ''
    SE_ItemViewItemText = None # (!) real value is ''
    SE_LabelLayoutItem = None # (!) real value is ''
    SE_LineEditContents = None # (!) real value is ''
    SE_ProgressBarContents = None # (!) real value is ''
    SE_ProgressBarGroove = None # (!) real value is ''
    SE_ProgressBarLabel = None # (!) real value is ''
    SE_ProgressBarLayoutItem = None # (!) real value is ''
    SE_PushButtonContents = None # (!) real value is ''
    SE_PushButtonFocusRect = None # (!) real value is ''
    SE_PushButtonLayoutItem = None # (!) real value is ''
    SE_RadioButtonClickRect = None # (!) real value is ''
    SE_RadioButtonContents = None # (!) real value is ''
    SE_RadioButtonFocusRect = None # (!) real value is ''
    SE_RadioButtonIndicator = None # (!) real value is ''
    SE_RadioButtonLayoutItem = None # (!) real value is ''
    SE_ShapedFrameContents = None # (!) real value is ''
    SE_SliderFocusRect = None # (!) real value is ''
    SE_SliderLayoutItem = None # (!) real value is ''
    SE_SpinBoxLayoutItem = None # (!) real value is ''
    SE_TabBarScrollLeftButton = None # (!) real value is ''
    SE_TabBarScrollRightButton = None # (!) real value is ''
    SE_TabBarTabLeftButton = None # (!) real value is ''
    SE_TabBarTabRightButton = None # (!) real value is ''
    SE_TabBarTabText = None # (!) real value is ''
    SE_TabBarTearIndicator = None # (!) real value is ''
    SE_TabBarTearIndicatorLeft = None # (!) real value is ''
    SE_TabBarTearIndicatorRight = None # (!) real value is ''
    SE_TabWidgetLayoutItem = None # (!) real value is ''
    SE_TabWidgetLeftCorner = None # (!) real value is ''
    SE_TabWidgetRightCorner = None # (!) real value is ''
    SE_TabWidgetTabBar = None # (!) real value is ''
    SE_TabWidgetTabContents = None # (!) real value is ''
    SE_TabWidgetTabPane = None # (!) real value is ''
    SE_ToolBarHandle = None # (!) real value is ''
    SE_ToolBoxTabContents = None # (!) real value is ''
    SE_ToolButtonLayoutItem = None # (!) real value is ''
    SE_TreeViewDisclosureItem = None # (!) real value is ''
    SE_ViewItemCheckIndicator = None # (!) real value is ''
    SH_BlinkCursorWhenTextSelected = None # (!) real value is ''
    SH_Button_FocusPolicy = None # (!) real value is ''
    SH_ComboBox_AllowWheelScrolling = None # (!) real value is ''
    SH_ComboBox_LayoutDirection = None # (!) real value is ''
    SH_ComboBox_ListMouseTracking = None # (!) real value is ''
    SH_ComboBox_Popup = None # (!) real value is ''
    SH_ComboBox_PopupFrameStyle = None # (!) real value is ''
    SH_ComboBox_UseNativePopup = None # (!) real value is ''
    SH_CustomBase = None # (!) real value is ''
    SH_DialogButtonBox_ButtonsHaveIcons = None # (!) real value is ''
    SH_DialogButtonLayout = None # (!) real value is ''
    SH_DialogButtons_DefaultButton = None # (!) real value is ''
    SH_Dial_BackgroundRole = None # (!) real value is ''
    SH_DitherDisabledText = None # (!) real value is ''
    SH_DockWidget_ButtonsHaveFrame = None # (!) real value is ''
    SH_DrawMenuBarSeparator = None # (!) real value is ''
    SH_EtchDisabledText = None # (!) real value is ''
    SH_FocusFrame_AboveWidget = None # (!) real value is ''
    SH_FocusFrame_Mask = None # (!) real value is ''
    SH_FontDialog_SelectAssociatedText = None # (!) real value is ''
    SH_FormLayoutFieldGrowthPolicy = None # (!) real value is ''
    SH_FormLayoutFormAlignment = None # (!) real value is ''
    SH_FormLayoutLabelAlignment = None # (!) real value is ''
    SH_FormLayoutWrapPolicy = None # (!) real value is ''
    SH_GroupBox_TextLabelColor = None # (!) real value is ''
    SH_GroupBox_TextLabelVerticalAlignment = None # (!) real value is ''
    SH_Header_ArrowAlignment = None # (!) real value is ''
    SH_ItemView_ActivateItemOnSingleClick = None # (!) real value is ''
    SH_ItemView_ArrowKeysNavigateIntoChildren = None # (!) real value is ''
    SH_ItemView_ChangeHighlightOnFocus = None # (!) real value is ''
    SH_ItemView_DrawDelegateFrame = None # (!) real value is ''
    SH_ItemView_EllipsisLocation = None # (!) real value is ''
    SH_ItemView_MovementWithoutUpdatingSelection = None # (!) real value is ''
    SH_ItemView_PaintAlternatingRowColorsForEmptyArea = None # (!) real value is ''
    SH_ItemView_ScrollMode = None # (!) real value is ''
    SH_ItemView_ShowDecorationSelected = None # (!) real value is ''
    SH_LineEdit_PasswordCharacter = None # (!) real value is ''
    SH_LineEdit_PasswordMaskDelay = None # (!) real value is ''
    SH_ListViewExpand_SelectMouseType = None # (!) real value is ''
    SH_MainWindow_SpaceBelowMenuBar = None # (!) real value is ''
    SH_MenuBar_AltKeyNavigation = None # (!) real value is ''
    SH_MenuBar_MouseTracking = None # (!) real value is ''
    SH_Menu_AllowActiveAndDisabled = None # (!) real value is ''
    SH_Menu_FadeOutOnHide = None # (!) real value is ''
    SH_Menu_FillScreenWithScroll = None # (!) real value is ''
    SH_Menu_FlashTriggeredItem = None # (!) real value is ''
    SH_Menu_KeyboardSearch = None # (!) real value is ''
    SH_Menu_Mask = None # (!) real value is ''
    SH_Menu_MouseTracking = None # (!) real value is ''
    SH_Menu_Scrollable = None # (!) real value is ''
    SH_Menu_SelectionWrap = None # (!) real value is ''
    SH_Menu_SloppySubMenus = None # (!) real value is ''
    SH_Menu_SpaceActivatesItem = None # (!) real value is ''
    SH_Menu_SubMenuDontStartSloppyOnLeave = None # (!) real value is ''
    SH_Menu_SubMenuPopupDelay = None # (!) real value is ''
    SH_Menu_SubMenuResetWhenReenteringParent = None # (!) real value is ''
    SH_Menu_SubMenuSloppyCloseTimeout = None # (!) real value is ''
    SH_Menu_SubMenuSloppySelectOtherActions = None # (!) real value is ''
    SH_Menu_SubMenuUniDirection = None # (!) real value is ''
    SH_Menu_SubMenuUniDirectionFailCount = None # (!) real value is ''
    SH_Menu_SupportsSections = None # (!) real value is ''
    SH_MessageBox_CenterButtons = None # (!) real value is ''
    SH_MessageBox_TextInteractionFlags = None # (!) real value is ''
    SH_MessageBox_UseBorderForButtonSpacing = None # (!) real value is ''
    SH_PrintDialog_RightAlignButtons = None # (!) real value is ''
    SH_ProgressDialog_CenterCancelButton = None # (!) real value is ''
    SH_ProgressDialog_TextLabelAlignment = None # (!) real value is ''
    SH_RequestSoftwareInputPanel = None # (!) real value is ''
    SH_RichText_FullWidthSelection = None # (!) real value is ''
    SH_RubberBand_Mask = None # (!) real value is ''
    SH_ScrollBar_ContextMenu = None # (!) real value is ''
    SH_ScrollBar_LeftClickAbsolutePosition = None # (!) real value is ''
    SH_ScrollBar_MiddleClickAbsolutePosition = None # (!) real value is ''
    SH_ScrollBar_RollBetweenButtons = None # (!) real value is ''
    SH_ScrollBar_ScrollWhenPointerLeavesControl = None # (!) real value is ''
    SH_ScrollBar_StopMouseOverSlider = None # (!) real value is ''
    SH_ScrollBar_Transient = None # (!) real value is ''
    SH_ScrollView_FrameOnlyAroundContents = None # (!) real value is ''
    SH_Slider_AbsoluteSetButtons = None # (!) real value is ''
    SH_Slider_PageSetButtons = None # (!) real value is ''
    SH_Slider_SloppyKeyEvents = None # (!) real value is ''
    SH_Slider_SnapToValue = None # (!) real value is ''
    SH_Slider_StopMouseOverSlider = None # (!) real value is ''
    SH_SpellCheckUnderlineStyle = None # (!) real value is ''
    SH_SpinBox_AnimateButton = None # (!) real value is ''
    SH_SpinBox_ButtonsInsideFrame = None # (!) real value is ''
    SH_SpinBox_ClickAutoRepeatRate = None # (!) real value is ''
    SH_SpinBox_ClickAutoRepeatThreshold = None # (!) real value is ''
    SH_SpinBox_KeyPressAutoRepeatRate = None # (!) real value is ''
    SH_SpinControls_DisableOnBounds = None # (!) real value is ''
    SH_Splitter_OpaqueResize = None # (!) real value is ''
    SH_TabBar_Alignment = None # (!) real value is ''
    SH_TabBar_ChangeCurrentDelay = None # (!) real value is ''
    SH_TabBar_CloseButtonPosition = None # (!) real value is ''
    SH_TabBar_ElideMode = None # (!) real value is ''
    SH_TabBar_PreferNoArrows = None # (!) real value is ''
    SH_TabBar_SelectMouseType = None # (!) real value is ''
    SH_Table_GridLineColor = None # (!) real value is ''
    SH_TabWidget_DefaultTabPosition = None # (!) real value is ''
    SH_TextControl_FocusIndicatorTextCharFormat = None # (!) real value is ''
    SH_TitleBar_AutoRaise = None # (!) real value is ''
    SH_TitleBar_ModifyNotification = None # (!) real value is ''
    SH_TitleBar_NoBorder = None # (!) real value is ''
    SH_TitleBar_ShowToolTipsOnButtons = None # (!) real value is ''
    SH_ToolBar_Movable = None # (!) real value is ''
    SH_ToolBox_SelectedPageTitleBold = None # (!) real value is ''
    SH_ToolButtonStyle = None # (!) real value is ''
    SH_ToolButton_PopupDelay = None # (!) real value is ''
    SH_ToolTipLabel_Opacity = None # (!) real value is ''
    SH_ToolTip_FallAsleepDelay = None # (!) real value is ''
    SH_ToolTip_Mask = None # (!) real value is ''
    SH_ToolTip_WakeUpDelay = None # (!) real value is ''
    SH_UnderlineShortcut = None # (!) real value is ''
    SH_Widget_Animate = None # (!) real value is ''
    SH_Widget_Animation_Duration = None # (!) real value is ''
    SH_Widget_ShareActivation = None # (!) real value is ''
    SH_WindowFrame_Mask = None # (!) real value is ''
    SH_WizardStyle = None # (!) real value is ''
    SH_Workspace_FillSpaceOnMaximize = None # (!) real value is ''
    SP_ArrowBack = None # (!) real value is ''
    SP_ArrowDown = None # (!) real value is ''
    SP_ArrowForward = None # (!) real value is ''
    SP_ArrowLeft = None # (!) real value is ''
    SP_ArrowRight = None # (!) real value is ''
    SP_ArrowUp = None # (!) real value is ''
    SP_BrowserReload = None # (!) real value is ''
    SP_BrowserStop = None # (!) real value is ''
    SP_CommandLink = None # (!) real value is ''
    SP_ComputerIcon = None # (!) real value is ''
    SP_CustomBase = None # (!) real value is ''
    SP_DesktopIcon = None # (!) real value is ''
    SP_DialogApplyButton = None # (!) real value is ''
    SP_DialogCancelButton = None # (!) real value is ''
    SP_DialogCloseButton = None # (!) real value is ''
    SP_DialogDiscardButton = None # (!) real value is ''
    SP_DialogHelpButton = None # (!) real value is ''
    SP_DialogNoButton = None # (!) real value is ''
    SP_DialogOkButton = None # (!) real value is ''
    SP_DialogOpenButton = None # (!) real value is ''
    SP_DialogResetButton = None # (!) real value is ''
    SP_DialogSaveButton = None # (!) real value is ''
    SP_DialogYesButton = None # (!) real value is ''
    SP_DirClosedIcon = None # (!) real value is ''
    SP_DirHomeIcon = None # (!) real value is ''
    SP_DirIcon = None # (!) real value is ''
    SP_DirLinkIcon = None # (!) real value is ''
    SP_DirLinkOpenIcon = None # (!) real value is ''
    SP_DirOpenIcon = None # (!) real value is ''
    SP_DockWidgetCloseButton = None # (!) real value is ''
    SP_DriveCDIcon = None # (!) real value is ''
    SP_DriveDVDIcon = None # (!) real value is ''
    SP_DriveFDIcon = None # (!) real value is ''
    SP_DriveHDIcon = None # (!) real value is ''
    SP_DriveNetIcon = None # (!) real value is ''
    SP_FileDialogBack = None # (!) real value is ''
    SP_FileDialogContentsView = None # (!) real value is ''
    SP_FileDialogDetailedView = None # (!) real value is ''
    SP_FileDialogEnd = None # (!) real value is ''
    SP_FileDialogInfoView = None # (!) real value is ''
    SP_FileDialogListView = None # (!) real value is ''
    SP_FileDialogNewFolder = None # (!) real value is ''
    SP_FileDialogStart = None # (!) real value is ''
    SP_FileDialogToParent = None # (!) real value is ''
    SP_FileIcon = None # (!) real value is ''
    SP_FileLinkIcon = None # (!) real value is ''
    SP_LineEditClearButton = None # (!) real value is ''
    SP_MediaPause = None # (!) real value is ''
    SP_MediaPlay = None # (!) real value is ''
    SP_MediaSeekBackward = None # (!) real value is ''
    SP_MediaSeekForward = None # (!) real value is ''
    SP_MediaSkipBackward = None # (!) real value is ''
    SP_MediaSkipForward = None # (!) real value is ''
    SP_MediaStop = None # (!) real value is ''
    SP_MediaVolume = None # (!) real value is ''
    SP_MediaVolumeMuted = None # (!) real value is ''
    SP_MessageBoxCritical = None # (!) real value is ''
    SP_MessageBoxInformation = None # (!) real value is ''
    SP_MessageBoxQuestion = None # (!) real value is ''
    SP_MessageBoxWarning = None # (!) real value is ''
    SP_TitleBarCloseButton = None # (!) real value is ''
    SP_TitleBarContextHelpButton = None # (!) real value is ''
    SP_TitleBarMaxButton = None # (!) real value is ''
    SP_TitleBarMenuButton = None # (!) real value is ''
    SP_TitleBarMinButton = None # (!) real value is ''
    SP_TitleBarNormalButton = None # (!) real value is ''
    SP_TitleBarShadeButton = None # (!) real value is ''
    SP_TitleBarUnshadeButton = None # (!) real value is ''
    SP_ToolBarHorizontalExtensionButton = None # (!) real value is ''
    SP_ToolBarVerticalExtensionButton = None # (!) real value is ''
    SP_TrashIcon = None # (!) real value is ''
    SP_VistaShield = None # (!) real value is ''
    StandardPixmap = None # (!) real value is ''
    State = None # (!) real value is ''
    StateFlag = None # (!) real value is ''
    State_Active = None # (!) real value is ''
    State_AutoRaise = None # (!) real value is ''
    State_Bottom = None # (!) real value is ''
    State_Children = None # (!) real value is ''
    State_DownArrow = None # (!) real value is ''
    State_Editing = None # (!) real value is ''
    State_Enabled = None # (!) real value is ''
    State_FocusAtBorder = None # (!) real value is ''
    State_HasFocus = None # (!) real value is ''
    State_Horizontal = None # (!) real value is ''
    State_Item = None # (!) real value is ''
    State_KeyboardFocusChange = None # (!) real value is ''
    State_Mini = None # (!) real value is ''
    State_MouseOver = None # (!) real value is ''
    State_NoChange = None # (!) real value is ''
    State_None = None # (!) real value is ''
    State_Off = None # (!) real value is ''
    State_On = None # (!) real value is ''
    State_Open = None # (!) real value is ''
    State_Raised = None # (!) real value is ''
    State_ReadOnly = None # (!) real value is ''
    State_Selected = None # (!) real value is ''
    State_Sibling = None # (!) real value is ''
    State_Small = None # (!) real value is ''
    State_Sunken = None # (!) real value is ''
    State_Top = None # (!) real value is ''
    State_UpArrow = None # (!) real value is ''
    State_Window = None # (!) real value is ''
    staticMetaObject = None # (!) real value is ''
    StyleHint = None # (!) real value is ''
    SubControl = None # (!) real value is ''
    SubControls = None # (!) real value is ''
    SubElement = None # (!) real value is ''


